### ISSUE TITLE
view目录下可以在分子目录么?

### ISSUE THREAD

**Issue by FengZeming** [mobejs/mobe#49]
例如 :view 下放置 index.html
          view/paper/list.html  
  view 下的 paper 目录 放置list.html

fms.view({
		     type: 'get',
    		url: '/gel/em/paper/list',
    		title: "试卷管理-试卷查看",
    		template: "/paper/list.html"
	});
我现在这么写的不好使

**Comment by nimojs** [comment]
报错了么？ 报错信息发来看下

**Comment by FengZeming** [comment]
Error: Failed to lookup view "list.html" in views directory "E:\fzm\hbuilder\静态项目/view"
   at EventEmitter.render (E:\fzm\hbuilder\静态项目\node_modules\.npminstall\express\4.14.0\express\lib\application.js:579:17)
   at ServerResponse.render (E:\fzm\hbuilder\静态项目\node_modules\.npminstall\express\4.14.0\express\lib\response.js:960:7)
   at E:\fzm\hbuilder\静态项目\fms.js:101:8
   at Layer.handle [as handle_request] (E:\fzm\hbuilder\静态项目\node_modules\.npminstall\express\4.14.0\express\lib\router\layer.js:95:5)
   at trim_prefix (E:\fzm\hbuilder\静态项目\node_modules\.npminstall\express\4.14.0\express\lib\router\index.js:312:13)
   at E:\fzm\hbuilder\静态项目\node_modules\.npminstall\express\4.14.0\express\lib\router\index.js:280:7
   at Function.process_params (E:\fzm\hbuilder\静态项目\node_modules\.npminstall\express\4.14.0\express\lib\router\index.js:330:12)
   at next (E:\fzm\hbuilder\静态项目\node_modules\.npminstall\express\4.14.0\express\lib\router\index.js:271:10)
   at E:\fzm\hbuilder\静态项目\node_modules\.npminstall\body-parser\1.15.2\body-parser\lib\read.js:129:5
   at invokeCallback (E:\fzm\hbuilder\静态项目\node_modules\.npminstall\raw-body\2.1.7\raw-body\index.js:262:16)

**Comment by FengZeming** [comment]
![image](https://cloud.githubusercontent.com/assets/12960884/16475718/6331e9a2-3eb3-11e6-940d-14a47797ebbe.png)

**Comment by FengZeming** [comment]
![image](https://cloud.githubusercontent.com/assets/12960884/16475734/7e9b0336-3eb3-11e6-9ce3-36865296096d.png)

**Comment by FengZeming** [comment]
![image](https://cloud.githubusercontent.com/assets/12960884/16475755/ab1989be-3eb3-11e6-8dee-daf297834220.png)

**Comment by FengZeming** [comment]
![image](https://cloud.githubusercontent.com/assets/12960884/16475771/d0382354-3eb3-11e6-96d3-54d4810b6e3c.png)

**Comment by FengZeming** [comment]
![image](https://cloud.githubusercontent.com/assets/12960884/16475787/f9531172-3eb3-11e6-80ad-d68db889b005.png)

**Comment by FengZeming** [comment]
![image](https://cloud.githubusercontent.com/assets/12960884/16475794/085ecf08-3eb4-11e6-8185-48aeb0fd78f6.png)

**Comment by nimojs** [comment]
```
template: ''app/em/paper/list.html"
```
去掉前面的 `/` 试试。如果还不行加下QQ群：379019353 发我文件我调试下
